/**
 * Build digital products catalog artifacts from catalog/.
 * Run: node scripts/build-catalog.mjs
 *
 * Outputs:
 *   catalog-pricing.js — UI pricing (edit catalog/products/.../product.json)
 *   digital-products.html — injects how-to guides from product how-to.*.md
 */
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';
import { mdToGuideHtml } from './lib/guide-markdown.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const CATALOG_DIR = join(ROOT, 'catalog');

function readJson(path) {
  return JSON.parse(readFileSync(path, 'utf8'));
}

function formatAmount(amount, lang) {
  const s = Number(amount).toFixed(2);
  return lang === 'en' ? s : s.replace('.', ',');
}

function priceWithSymbol(amount, lang, symbol) {
  return symbol + formatAmount(amount, lang);
}

function applyGuideTokens(md, product, lang) {
  const { plans, symbol, appUrl } = product;
  return md
    .replace(/\{\{price\.oneTime\}\}/g, priceWithSymbol(plans.oneTime.amount, lang, symbol))
    .replace(/\{\{price\.subscription\}\}/g, priceWithSymbol(plans.subscription.amount, lang, symbol))
    .replace(/\{\{app\.url\}\}/g, appUrl);
}

function loadProduct(productEntry) {
  const dir = join(CATALOG_DIR, productEntry.dir);
  const product = readJson(join(dir, 'product.json'));
  if (product.id !== productEntry.id) {
    throw new Error(`Product id mismatch in ${dir}`);
  }
  return { dir, product };
}

function buildPricingJs(products) {
  const catalog = {};
  for (const { product } of products) {
    catalog[product.id] = {
      currency: product.currency,
      symbol: product.symbol,
      oneTime: product.plans.oneTime,
      subscription: product.plans.subscription,
      labels: product.pricingLabels
    };
  }

  const body = `/**
 * GENERATED by scripts/build-catalog.mjs — do not edit by hand.
 * Edit catalog/products/.../product.json then run npm run build:catalog
 */
(function (global) {
  var CATALOG = ${JSON.stringify(catalog, null, 2)};

  function formatAmount(amount, lang) {
    var s = Number(amount).toFixed(2);
    return lang === 'en' ? s : s.replace('.', ',');
  }

  function priceWithSymbol(catalogEntry, amount, lang) {
    return catalogEntry.symbol + formatAmount(amount, lang);
  }

  function labels(catalogEntry, lang) {
    return catalogEntry.labels[lang] || catalogEntry.labels.en;
  }

  function renderCompact(productId, lang) {
    var c = CATALOG[productId];
    if (!c) return '';
    var L = labels(c, lang);
    var ot = priceWithSymbol(c, c.oneTime.amount, lang);
    var sub = priceWithSymbol(c, c.subscription.amount, lang);
    return (
      '<div class="product-pricing-compact" role="group" aria-label="' +
      L.pricesHeading +
      '">' +
      '<p class="product-pricing-compact-heading font-syne text-[10px] uppercase tracking-widest text-emerald/90 mb-2">' +
      L.pricesHeading +
      '</p>' +
      '<ul class="product-pricing-compact-list">' +
      '<li><span class="product-pricing-amount">' +
      ot +
      '</span> <span class="product-pricing-meta">' +
      L.compactOne +
      '</span></li>' +
      '<li><span class="product-pricing-amount">' +
      sub +
      L.perMonth +
      '</span> <span class="product-pricing-meta">' +
      L.compactSub +
      '</span></li>' +
      '</ul></div>'
    );
  }

  function renderFull(productId, lang) {
    var c = CATALOG[productId];
    if (!c) return '';
    var L = labels(c, lang);
    var ot = priceWithSymbol(c, c.oneTime.amount, lang);
    var sub = priceWithSymbol(c, c.subscription.amount, lang);
    return (
      '<section class="product-pricing-full" aria-labelledby="pricing-full-' +
      productId +
      '-' +
      lang +
      '">' +
      '<h3 id="pricing-full-' +
      productId +
      '-' +
      lang +
      '" class="font-syne text-sm font-semibold text-emerald mb-3">' +
      L.pricesHeading +
      '</h3>' +
      '<div class="product-pricing-grid">' +
      '<article class="product-pricing-card">' +
      '<span class="product-pricing-badge">' +
      L.oneTimeBadge +
      '</span>' +
      '<p class="product-pricing-card-price">' +
      ot +
      '</p>' +
      '<p class="product-pricing-card-title">' +
      L.oneTimeTitle +
      '</p>' +
      '<p class="product-pricing-card-desc">' +
      L.oneTimeDesc +
      '</p>' +
      '</article>' +
      '<article class="product-pricing-card">' +
      '<span class="product-pricing-badge product-pricing-badge--sub">' +
      L.subBadge +
      '</span>' +
      '<p class="product-pricing-card-price">' +
      sub +
      '<span class="product-pricing-card-period">' +
      L.perMonth +
      '</span></p>' +
      '<p class="product-pricing-card-title">' +
      L.subTitle +
      '</p>' +
      '<p class="product-pricing-card-desc">' +
      L.subDesc +
      '</p>' +
      '</article></div></section>'
    );
  }

  function mount() {
    document.querySelectorAll('.product-pricing-slot').forEach(function (slot) {
      var productId = slot.getAttribute('data-product-id');
      if (!productId || !CATALOG[productId]) return;
      var article = slot.closest('article[data-lang]');
      if (!article) return;
      var lang = article.getAttribute('data-lang');
      var view = slot.getAttribute('data-pricing-view');
      slot.innerHTML = view === 'full' ? renderFull(productId, lang) : renderCompact(productId, lang);
    });
  }

  global.CatalogPricing = {
    CATALOG: CATALOG,
    mount: mount
  };
})(typeof window !== 'undefined' ? window : globalThis);
`;

  writeFileSync(join(ROOT, 'catalog-pricing.js'), body, 'utf8');
  console.log('  ✓ catalog-pricing.js');
}

function replaceGuideInArticle(articleHtml, guideHtml) {
  return articleHtml.replace(
    /(<div class="product-guide-panel px-4 pb-6 md:px-6">)[\s\S]*?(<\/div>\s*<\/details>\s*\n\s*<\/div>\s*\n\s*<\/details>)/,
    `$1\n        ${guideHtml}\n        $2`
  );
}

function injectGuides(html, productId, guidesByLang) {
  for (const lang of ['ru', 'en', 'lv']) {
    const guideHtml = guidesByLang[lang];
    if (!guideHtml) continue;
    const re = new RegExp(`(<article data-lang="${lang}"[^>]*>[\\s\\S]*?)(<\\/article>)`, 'm');
    html = html.replace(re, (_, body, close) => replaceGuideInArticle(body, guideHtml) + close);
  }
  return html;
}

function buildGuidesForProduct(dir, product) {
  const guides = {};
  for (const lang of ['ru', 'en', 'lv']) {
    const path = join(dir, `how-to.${lang}.md`);
    if (!existsSync(path)) {
      console.warn(`  ⚠ missing ${path}`);
      continue;
    }
    let md = readFileSync(path, 'utf8');
    md = applyGuideTokens(md, product, lang);
    guides[lang] = mdToGuideHtml(md);
  }
  return guides;
}

console.log('Building digital products catalog…');
const index = readJson(join(CATALOG_DIR, 'catalog.json'));
const loaded = index.products.map((entry) => loadProduct(entry));

buildPricingJs(loaded);

let html = readFileSync(join(ROOT, 'digital-products.html'), 'utf8');

for (const { dir, product } of loaded) {
  const guides = buildGuidesForProduct(dir, product);
  html = injectGuides(html, product.id, guides);
  console.log(`  ✓ how-to injected: ${product.id}`);
}

writeFileSync(join(ROOT, 'digital-products.html'), html, 'utf8');
console.log('  ✓ digital-products.html (guide sections)');
console.log('Done.');
